# Generated by Django 6.0.7 on 2026-07-12 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mm_per_px", models.FloatField(blank=True, null=True)),
                ("camera_height_mm", models.FloatField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("device_token_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("gps_accuracy_m", models.FloatField(blank=True, null=True)),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("overlay_path", models.CharField(blank=True, max_length=500)),
                ("crack_length_mm", models.FloatField(blank=True, null=True)),
                ("crack_width_mm", models.FloatField(blank=True, null=True)),
                ("crack_area_mm2", models.FloatField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("critical", "critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "unreviewed"),
                            ("reviewed", "reviewed"),
                            ("flagged", "flagged"),
                            ("closed", "closed"),
                        ],
                        default="unreviewed",
                        max_length=15,
                    ),
                ),
                ("measurement_source", models.CharField(default="auto", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="Engineer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("code", models.CharField(blank=True, max_length=4)),
                ("avatar", models.FileField(blank=True, upload_to="avatars/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engineer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_progress", "in_progress"),
                            ("resolved", "resolved"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="api.engineer",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="api.detection",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_tickets",
                        to="api.engineer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
