# Generated by Django 6.0.7 on 2026-07-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detection",
            name="gps_accuracy_m",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="severity",
        ),
    ]
